resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: react-components/master
  type: git
  source:
    uri: git@github.com:buildo/react-components
    branch: master
    private_key: ((private-key))

- name: pr
  type: pull-request
  source:
    repository: buildo/react-components
    access_token: ((github-token))

jobs:
- name: test
  plan:
  - get: react-components
    resource: react-components/master
    trigger: true
  - task: test
    file: react-components/ci/tasks/test.yml

- name: pr-test
  plan:
  - get: react-components
    resource: pr
    trigger: true
    version: every
  - put: pr
    params:
      path: react-components
      status: pending
      context: concourse
  - do:
    - task: test
      file: react-components/ci/tasks/test.yml
    - task: build-preview
        file: react-components/ci/tasks/build-preview.yml
        attempts: 2
    - task: upload-preview
      file: react-components/ci/tasks/upload-preview.yml
      params:
        AWS_ACCESS_KEY_ID: ((preview-access-key))
        AWS_SECRET_ACCESS_KEY: ((preview-secret-key))
    on_success:
      put: pr
      params:
        path: react-components
        status: success
        context: concourse
    on_failure:
      put: pr
      params:
        path: react-components
        status: failure
        context: concourse
