pipeline:

  restore-cache:
      image: drillster/drone-volume-cache
      restore: true
      mount:
        - ./node_modules
      volumes:
        - /tmp/cache:/cache

  install-deps:
    image: node:8
    environment:
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm i

  test:
    group: parallel
    image: node:8
    commands:
      - npm run prettier-check
      - npm run typecheck
      - npm test

  generate-changelog:
    image: node:8
    secrets: [ changelog_github_token ]
    commands:
      - git pull --ff-only origin master
      - git branch --set-upstream-to=origin/master master
      - git config --global push.default simple
      - git config --global user.name "nemobot";
      - git config --global user.email "our-bots@buildo.io";
      - node_modules/smooth-release/smooth-release --changelog --token=$CHANGELOG_GITHUB_TOKEN --no-validations --no-gh-release --no-npm-version --no-npm-publish
    when:
      branch: master

  publishReleaseOnGitHub:
    image: node:8
    secrets: [ changelog_github_token ]
    commands:
      - node_modules/smooth-release/smooth-release --gh-release --token=$CHANGELOG_GITHUB_TOKEN --no-validations --no-changelog --no-npm-version --no-npm-publish
    when:
      branch: master

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

