platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8
inputs:
  - name: react-components
caches:
  - path: react-components/node_modules
run:
  path: react-components/ci/tasks/test.sh
