platform: linux

image_resource:
  type: docker-image
  source:
    repository: mesosphere/aws-cli

inputs:
  - name: react-components
  - name: preview

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: react-components/ci/tasks/upload-preview.sh
