resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: master
  type: git
  source:
    uri: git@github.com:buildo/react-components
    branch: master
    private_key: ((private-key))

jobs:
- name: test
  plan:
  - get: react-components
    resource: master
    trigger: true
  - task: test
    config: &test_config
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: 8
      inputs:
        - name: react-components
      caches:
        - path: react-components/node_modules
      run:
        path: sh
        args:
          - -c
          - |
            set -e
            cd react-components
            yarn install --no-progress
            yarn typecheck
            yarn prettier-check
            yarn test
