resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: master
  type: git
  source:
    uri: git@github.com:buildo/react-components
    branch: master
    private_key: ((private-key))

- name: pr
  type: pull-request
  source:
    repository: buildo/react-components
    access_token: ((github-token))

jobs:
- name: test
  plan:
  - get: react-components
    resource: master
    trigger: true
  - task: test
    config: &test_config
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: 8
      inputs:
        - name: react-components
      caches:
        - path: react-components/node_modules
      run:
        path: sh
        args:
          - -c
          - |
            set -e
            cd react-components
            yarn install --no-progress
            yarn typecheck
            yarn prettier-check
            yarn test

- name: pr-test
  plan:
  - get: react-components
    resource: pr
    trigger: true
    version: every
  - put: pr
    params:
      path: react-components
      status: pending
      context: concourse
  - task: test
    config:
      <<: *test_config
    on_success:
      put: pr
      params:
        path: react-components
        status: success
        context: concourse
    on_failure:
      put: pr
      params:
        path: react-components
        status: failure
        context: concourse
