resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: master
  type: git
  source:
    uri: git@github.com:buildo/react-components
    branch: master
    private_key: ((private-key))

- name: pr
  type: pull-request
  source:
    repository: buildo/react-components
    access_token: ((github-token))

jobs:
- name: test
  plan:
  - get: react-components
    resource: master
    trigger: true
  - task: test
    file: react-components/ci/test_config.yml

- name: pr-test
  plan:
  - get: react-components
    resource: pr
    trigger: true
    version: every
  - put: pr
    params:
      path: react-components
      status: pending
      context: concourse
  - task: test
    file: react-components/ci/test_config.yml
    on_success:
      put: pr
      params:
        path: react-components
        status: success
        context: concourse
    on_failure:
      put: pr
      params:
        path: react-components
        status: failure
        context: concourse
